### ISSUE TITLE
Using '::find()' on nonexistent resources returns an Error

### ISSUE THREAD

**Issue by zackkrida** [myleshyson/laravel-quickbooks#1]
If you try to 'find', say, a customer, with an invalid ID, the following happens:

![screen shot 2017-01-09 at 12 39 50 pm](https://cloud.githubusercontent.com/assets/6351754/21776487/cd9927cc-d668-11e6-9949-7dc3f01ff320.png)

My Code:
```
use Myleshyson\LaravelQuickBooks\Facades\Customer;

// There is no customer with an id of '11'
Customer::find(11);

```

The problematic function (Customer.php in this example): 

```
 public function find($id)
    {
        $this->service = new \QuickBooks_IPP_Service_Customer();
        return $this->service->query($this->context, $this->realm, "SELECT * FROM Customer WHERE Id = '$id' ")[0];
    }
```

**Comment by myleshyson** [comment]
Hmm thanks for noticing that. It would be better if an exception were thrown instead. Working on it now.

**Comment by myleshyson** [comment]
Alright it should now return 'Looks like this id does not exist';

**Comment by zackkrida** [comment]
Nice! 👍
