### ISSUE TITLE
TimeActivity

### ISSUE THREAD

**Issue by jimiguru** [myleshyson/laravel-quickbooks#13]
I'm getting an error with the TimeActivity object, what am I doing wrong?

HandleExceptions->handleError(8, 'Undefined variable: account'

TimeActivity::create([
      'NameOf' => 'Employee',
      'EmployeeRef' => [
        'Id' => 000,
        'Name' => 'Test Man'
      ],
      'Hours' => 5

 ]);

**Comment by myleshyson** [comment]
Hmm yea that's weird. Is it only happening on the TimeActivity object?

**Comment by jimiguru** [comment]
Yes.

**Comment by myleshyson** [comment]
Hey I know this is a really late response. I just published a release that I think fixes the problem.
