### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by marabesi** [myleshyson/laravel-quickbooks#15]
Where I can find all possible examples to use this package?

The README.md has Customer/Invoice, but I was wondering where I can have examples in Accounts and Journal Entry.

**Comment by myleshyson** [comment]
https://developer.intuit.com/docs/api/accounting

Here is the quickbooks reference. I listed the services that this package doesn't support. Those two examples were just to show how to interact with the package when making api calls. For each individual option you'll have to look in the actual quickbooks api reference.
