### ISSUE TITLE
Getting a weird load() error 

### ISSUE THREAD

**Issue by robmpreston** [myleshyson/laravel-quickbooks#16]
We're trying to use this for a project and getting this error: 
>                                                                                                                                                                    
>   [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                          
>   QuickBooks_Loader::load(): Failed opening required '/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Driver/.php' (inclu  
>   de_path='.::/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks')                                                                       
>                        

I've done all the basic setup on the readme, just trying a simple connection test... environment variables are set

for some reason its trying to open a file ".php" which makes me think an environment variable isnt set right or something similar, but everything looks good.

This is on Laravel 5.4 btw

**Comment by myleshyson** [comment]
Hmm that's weird. I just tried to connect on a fresh installation of Laravel and I'm not getting that error. Did you require the dev-master version of consolibyte/quickbooks? Are you using php 7?

**Comment by robmpreston** [comment]
Laravel 5.4.

dev-master version of consolibyte/quickbooks

php 7.1

**Comment by myleshyson** [comment]
What is exactly is giving you that error?  I just released a new version, 1.04. Maybe try that?

**Comment by robmpreston** [comment]
Hm, no change

                                                                                                                                                                     
>   [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                            
>   QuickBooks_Loader::load(): Failed opening required '/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Driver/.php' (include  
>   _path='.::/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks')                                                                           
>                                                                                                                                                                      
> 
> 
> Warning: Uncaught ErrorException: require_once(/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Driver/.php): failed to open stream: No such file or directory in /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php:56
> Stack trace:
> #0 /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php(56): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require_once(/U...', '/Users/robertpr...', 56, Array)
> #1 /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php(56): require_once()
> #2 /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php(104): QuickBooks_Loader::load('/QuickBooks/Dri...', false)
> #3 [internal function]: QuickBooks_Loader::__autoload('QuickBooks_Driv...')
> #4 [internal function]: spl_autoload_call('QuickBooks_Driv...')
> #5 /Users/robertpreston/Documents/source/signcode/vendor/consolibyt in /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php on line 56
> 
> Fatal error: QuickBooks_Loader::load(): Failed opening required '/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Driver/.php' (include_path='.::/Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks') in /Users/robertpreston/Documents/source/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php on line 56

this is just on a call to:

  Connection::start();

**Comment by jonrobinson** [comment]
`Fatal error: QuickBooks_Loader::load(): Failed opening required '/home/vagrant/Code/signcode/vendor/consolibyte/quickbooks/QuickBooks/Driver/.php' (include_path='.:/usr/share/php:/home/vagrant/Code/signcode/vendor/consolibyte/quickbooks') in /home/vagrant/Code/signcode/vendor/consolibyte/quickbooks/QuickBooks/Loader.php on line 56`

This appears to be where the problem is.  I pretty much started with a fresh install of Laravel 54.  It appears it's adding a "/" to Driver.php (Driver/.php).  This is when running a unit test. Currently checking to see why.

**Comment by jonrobinson** [comment]
Nevermind it was because QB_DSN env variable wasn't set correctly.

**Comment by luisito07** [comment]
> Nevermind it was because QB_DSN env variable wasn't set correctly.
how did you set your QB_DSN env variable correctly ? I'm having the same problem. thanks in advance
