### ISSUE TITLE
what URL to add on oath url?

### ISSUE THREAD

**Issue by m3Lvs** [myleshyson/laravel-quickbooks#19]
Good Day Sir.. this wasnt an issue actually... but I was currently trying to use your plugin..  I have successfully installed it on my laravel fresh installation now I tried the 

```
use Myleshyson\LaravelQuickBooks\Facades\Connection;

"Route::get('/connect', function () {
  Connection::start();
});

```

I got redirected to my QUICKBOOKS account and asked me to authorized the app.. but when I clicked authorized I got redirected to 'http://quickbooks-app.dev.com' which I specified on .env file (which I think should happen) but when I tried accessing "/check-connection" I still got a 'false' reply.. should there be any code on controller on the specified route for example "QB_OAUTH_URL = http://quickbooks-app.dev.com" (this is a localhost)

**Comment by myleshyson** [comment]
Hmm yea I'm  not sure. The QB_OAUTH_URL should be whatever you call Connection::start() from. I just tried it and it worked for me .

my settings are:
QB_OAUTH_URL=http://quickbooks.dev/connect
QB_SUCCESS_URL= http://quickbooks.dev/

```php
Route::get('/', function () {
    dd(Connection::check()); //true after connecting through /connect
});

Route::get('/connect', function () {
    Connection::start();
});
```
