### ISSUE TITLE
Custom Fields in Invoice

### ISSUE THREAD

**Issue by zackkrida** [myleshyson/laravel-quickbooks#2]
Hi there,

I'm having some issues adding custom fields when I am creating invoices. Maybe you have some input?

## 1. DefenitionId vs. Id

So in the Quickbooks documentation they reference a "DefinitionId" for for custom fields, in your code you're using just `Id` (https://github.com/myleshyson/laravel-quickbooks/blob/master/src/Quickbooks.php#L406). This is fine, it just took me a bit to figure out.

So, that means this should work when creating an invoice:

```
            "CustomField" => [
                    "Id" => "2",
                    "Name" => "Season",
                    "Type" => "StringType",
                    "StringValue" => "Test 3"
            ],
```

However, I can't get my custom fields to save. I assumed for the 3 custom fields, the IDs are "1", "2", and "3" based on the [Quickbooks docs](https://developer.intuit.com/docs/0100_quickbooks_online/0200_dev_guides/accounting/custom_fields),  but I can't get any custom fields to actually save, even if the invoice submits.

## 2. Adding multiple custom fields

It doesn't look like there is support for multiple custom fields. When I try to add them like this:

```
 "CustomField" => [
                [
                    "Id" => "1",
                    "StringValue" => "Test 1"
                ],
                [
                    "Id" => "2",
                    "StringValue" => "Test 2"
                ],
                [
                    "Id" => "3",
                    "StringValue" => "Test 3"
                ]
 ],
```

I get the "2020: [Required param missing, need to supply the required value for the API, Required parameter CustomFieldValue.DefinitionId is missing in the request]". Do I just need to add multiple "CustomField" arrays to the Invoice array?

Thanks so much for this package -- it makes working with the terrible Quickbooks PHP SDK much better!

**Comment by myleshyson** [comment]
Hey Thanks for catching that. The custom fields object was calling the wrong things. I fixed that, changed 'id' to 'DefinitionId' to stay consistent with quickbooks and also added the ability to set all 3 custom fields. It should work fine now with the new release!

So now it would look like you presented
```php
"CustomField" => [
                [
                    "DefinitionId" => "1",
                    "StringValue" => "Test 1"
                ],
                [
                    "DefinitionId" => "2",
                    "StringValue" => "Test 2"
                ],
                [
                    "DefinitionId" => "3",
                    "StringValue" => "Test 3"
                ]
 ],

```

Yea I created this with the hopes people wouldn't have to go through the same I did hell trying to figure out the quickbooks api haha. I'm glad it's helpful 😄
