### ISSUE TITLE
Invoice::update Breaking due to bug

### ISSUE THREAD

**Issue by jideokus** [myleshyson/laravel-quickbooks#20]
Line 25 on [Invoice.php](https://github.com/myleshyson/laravel-quickbooks/blob/master/src/Services/Accounting/Invoice.php) has a typo on handleTransactionnData causing the function to break.

It should be handleTransactionData  (with 1 n)

**Comment by myleshyson** [comment]
Thanks, just fixed it.

**Comment by jideokus** [comment]
Awesome. Thanks
