### ISSUE TITLE
Exposing quickbook query() function to facade?

### ISSUE THREAD

**Issue by Trexology** [myleshyson/laravel-quickbooks#8]
How about exposing the query() function for developer to pass in their customized SQL query.

Currently is only restricted to the facade find() and get() method...

A even better will is to make it into "eloquent style" facade. that will make it very easy to use.

**Comment by myleshyson** [comment]
Hey good idea on exposing the query. Will push that up sometime today. As far as making it feel more like eloquent, that would be pretty cool. Feel free to open a pull request!

**Comment by myleshyson** [comment]
#9 
Exposed the query method on each service. You can call it like so

```php
Customer::query('Select * from CUSTOMER where ...');
```
